### ISSUE TITLE
Support architecture arm64

### ISSUE THREAD

**Issue by patricksadowski** [koenvzeijl/AspNetCore.SassCompiler#102]
**Is your feature request related to a problem? Please describe.**
We use several CI systems including arm64. Build stops with
```
/root/.nuget/packages/aspnetcore.sasscompiler/1.53.0/build/AspNetCore.SassCompiler.targets(11,5): error MSB4018: The "CompileSass" task failed unexpectedly. [/builds/[MASKED].csproj]
/root/.nuget/packages/aspnetcore.sasscompiler/1.53.0/build/AspNetCore.SassCompiler.targets(11,5): error MSB4018: System.ComponentModel.Win32Exception (8): An error occurred trying to start process '/root/.nuget/packages/aspnetcore.sasscompiler/1.53.0/build/../runtimes/linux-x64/sass' with working directory '/builds/[MASKED]'. Exec format error [/builds/[MASKED].csproj]
```

**Describe the solution you'd like**
Extend your GitHub Workflow `update-sass`

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by sleeuwen** [comment]
Hi @patricksadowski ,
Thanks for reporting the issue, it does look like dart-sass does provide linux-arm64 binaries which we can include in the nuget. This does need some extra changes as we currently always assume x64 architecture.
I'll try to get this included tomorrow and then release  v1.54.2 of which there is currently an open PR.

**Comment by br4mbor** [comment]
Just quick question. Are you going to include macos-arm64 libraries for Apple Silicon Macs?

**Comment by sleeuwen** [comment]
@patricksadowski @br4mbor I've just released v1.54.3 which include the binaries for linux-arm64 and macos-arm64. However, as I don't personally have an arm64 device to test this on, can you verify if it is working?

**Comment by patricksadowski** [comment]
If our CI system works then it's fixed. Hopefully, I can try it on monday.

**Comment by patricksadowski** [comment]
@sleeuwen Our CI system is able to execute 
`AspNetCore.SassCompiler`. Thank you 👍
