### ISSUE TITLE
Allow aliased file paths when importing through scss files

### ISSUE THREAD

**Issue by axekan** [koenvzeijl/AspNetCore.SassCompiler#109]
Add configuration for custom module paths similar to ESM. A feature when using JavaScript modules is that you can add something like this to jsconfig/tsconfig:

```
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "@constants/*": [
                "./src/constants/*"
            ],
            "@utils/*": [
                "./src/utils/*"
            ]
        }
    }
}
```

This will allow the compiler to use these paths to resolve imports in your different modules. Could something similar be done with sass imports?

I've run into a problem where I have many scoped scss files in my project, at different levels in the project structure. And something like this would be very useful.

**Describe the solution you'd like**

Instead of importing an scss file like this: `@import '../../../Styles/_global.scss'; `,
you could do something like: `@import '~globals/_global.scss'` or just `@import '_global.scss'`

**Additional context**

It appears webpack has a way to do this using something like this:
```
// Webpack config
{
  test: /\.scss$/,
  loader: 'sass-loader',
  options: {
    sassOptions: {
      includePaths: [path.resolve(__dirname, '<path to styles>')],
    },
  },
},
```
which you would then use like this:

```
@import 'filename.scss'; // Imported from <path to styles> folder.

.style {
  //...
}
```

**Comment by sleeuwen** [comment]
Hi @axekan , thanks for reporting the issue. As we use the dart-sass cli underneath to compile the scss files, we can make use of the --load-path option to do basically the same thing as what you described in your webpack example.

I will try to add a specific setting for this in the next few days. In the meantime, you can actually already do this yourself by making use of the "Arguments" setting (alongside your other SassCompiler settings) like so:
```json
{
    "Arguments": "--load-path Styles"
}
```
