### ISSUE TITLE
Source.scss -> Target.min.css

### ISSUE THREAD

**Issue by mikes-gh** [koenvzeijl/AspNetCore.SassCompiler#120]
**Is your feature request related to a problem? Please describe.**
I want to be able to define the name of the output file.
I am happy to PR this

**Describe the solution you'd like**
`[Obselete] `
`SourceFolder` and `TargetFolder`
in favour of
`Source` and `Target` parameters.
Check if the parameters are directories or files and follow appropriate logic.

Any of the following should be able to work

```json
{
  "SourceFolder": "Styles",
  "TargetFolder": "wwwroot/css",
  "Arguments": "--style=compressed",
}
```

```json
{
  "Source": "Styles",
  "Target": "wwwroot/css",
  "Arguments": "--style=compressed",
}
```

```json
{
  "Source": "Styles/MudBlazor.scss",
  "Target": "wwwroot/MudBlazor.min.css",
  "Arguments": "--style=compressed",
}
```

**Describe alternatives you've considered**
Renaming file after MSBuildTask completes but this over complicates the project file.
Dart SASS already does this natively

**Additional context**

**Comment by mikes-gh** [comment]
Another design could be `SourceTargetPairs []`

Its not my use case but is more flexible.

```json
{
    "SourceTargetPair": [
    {
     "Source": "Styles/MudBlazor.scss",
     "Target":  "wwwroot/MudBlazor.min.css"
     },
    {
     "Source": "Styles/MudBlazor1.scss",
     "Target":  "wwwroot/MudBlazor1.min.css"
     }]
  "Arguments": "--style=compressed",
}

**Comment by sleeuwen** [comment]
Hi @mikes-gh,
We directly pass the arguments to the dart-sass executable that does the conversion and creates the .css file. This does however mean that if you use a folder as the source you can't specify the resulting filename. You currently can already specify a filename for both SourceFolder and TargetFolder and I think that should work the same, however I agree it is confusing to have Folder in the setting.

I've wanted to allow multiple source/target folders/files so I think the approach in the last comment, at that point we can also allow different arguments per folder (and have the arguments outside of the pairs be the default if it is not specified for a specific pair).  I'll try to create something for this in the coming days.

**Comment by mikes-gh** [comment]
>You currently can already specify a filename for both SourceFolder and TargetFolder and I think that should work the same, however I agree it is confusing to have Folder in the setting.

AFAICS Specifying a filename gives an error that its not a folder.  It would be great if I could compile direct to a min.css filename as currently I have to add a target in my build for that and its a bit messy

**Comment by mikes-gh** [comment]
would you accept a PR for the SourceTargetPairs design or SourceTarget?

**Comment by mikes-gh** [comment]
Or an even simpler PR for `MinifiedFileExtension`?

**Comment by mikes-gh** [comment]
> Hi @mikes-gh, We directly pass the arguments to the dart-sass executable that does the conversion and creates the .css file. This does however mean that if you use a folder as the source you can't specify the resulting filename. You currently can already specify a filename for both SourceFolder and TargetFolder and I think that should work the same, however I agree it is confusing to have Folder in the setting.
> 
> I've wanted to allow multiple source/target folders/files so I think the approach in the last comment, at that point we can also allow different arguments per folder (and have the arguments outside of the pairs be the default if it is not specified for a specific pair). I'll try to create something for this in the coming days.

@sleeuwen We are going to create this feature in our own fork since as we need it now.  I would be happy to contribute it back to the original repo and use that as my preference would be to continue to support this excellent body of work.  Let me know if you're interested.
