### ISSUE TITLE
Exclude lib from build output when no runtime feature used

### ISSUE THREAD

**Issue by BDomzalski** [koenvzeijl/AspNetCore.SassCompiler#137]
I would like not to have AspNetCore.SassCompiler.dll included in the build results.

I do not use any library feature which acts at runtime. I would like to have the possibility to use only the MSBuild task without including the AspNetCore.SassCompiler in the resulting binaries (and .deps.json).

Is there a relatively simple way to achieve that? Is it possible to add such functionality to this library?

**Comment by adiessl** [comment]
You could do it as follows (see #85 as well):
```csproj
<PackageReference Include="AspNetCore.SassCompiler" Version="1.62.1">
  <PrivateAssets>all</PrivateAssets>
</PackageReference>
```

**Comment by sleeuwen** [comment]
This is currently the recommended way to exclude the dll from the publish output, we can't enable it by default as that would break being able to run the watcher during debugging, but as long as you don't use the watcher it is correct.
