### ISSUE TITLE
Source Maps Cannot be Disabled

### ISSUE THREAD

**Issue by AeonSake** [koenvzeijl/AspNetCore.SassCompiler#143]
**Describe the bug**
Applying the `--no-source-map` argument has no effect on the generated output. Source maps are always generated for both, normal import files and CSS isolation files.

**To Reproduce**
1. Add the `--no-source-map` flag to the `Arguments` property in either `appsettings.json > SassCompiler` or `sasscompiler.json` (it does not matter whether it is applied in the global `Arguments` property or in a configuration override)
2. Build the project in any configuration or publish the project
3. Inspect the produced output

**Expected behavior**
The `--no-source-map` should disable any source map generated by the underlying dart-sass compiler.

**Desktop (please complete the following information):**
 - OS: Windows 10 (22H2/19045.3086), Visual Studio Enterprise 2022 (17.6.3)
 - Version: **1.63.6**

**Additional context**
The issue occurs in any project environment, regardless of existing/upgraded project or brand-new project.

**Comment by sleeuwen** [comment]
Hi @AeonSake ,

I tested this in the sample projects in the repository and both (appsettings.json and sasscompiler.json) worked as expected for me. Can you verify it is not another plugin in visual studio that creates the source map by running `dotnet build` in the cli without having your project open in visual studio?
If it still generates the source map, the output of `dotnet build -v:n` can be useful in determining why this happens. If we can't find either `--source-map` or `--no-source-map` in the provided arguments, the default is to use `--source-map` for Debug builds and `--no-source-map` for Release builds. When this happens a message is logged as long as you have the verbosity enabled.

**Comment by AeonSake** [comment]
Hi @sleeuwen,
Thanks for the reply. I managed to get it working after changing the configuration, closing VS, deleting all map files manually and then restarting VS. For some reason the SASS compiler kept generating the map files regardless of what the configuration was. Maybe that was an issue because I had two solutions open at the same time (however, only one solution had the compiler NuGet installed).
I think the issue can be closed even though the behavior was quite strange.

**Comment by postb99** [comment]
Please can you provide in the readme some information about how to find the available arguments for dart-sass, such as `--no-source-map`? I think I finally have found the link to add: https://sass-lang.com/documentation/cli/dart-sass/

Thanks a lot
