### ISSUE TITLE
Support Windows on Arm

### ISSUE THREAD

**Issue by XenonAbe** [koenvzeijl/AspNetCore.SassCompiler#146]
On the Arm version of Windows 11, when loading the project, I receive the message `Your OS or CPU architecture is currently not supported.`.
Please support the ARM version of Windows. 

I believe it is possible to run the ARM64 version of Dart, but it appears to be still experimental. Therefore, I consider providing the option to run the x64 version of dart.exe as a viable solution to address the issue.

**Comment by sleeuwen** [comment]
@XenonAbe we use the assets that are built directly by the dart-sass project and linked to the releases, as they don't provide a windows ARM64 asset we also can't provide that.

**Comment by XenonAbe** [comment]
On ARM64-based Windows, when installing Sass using `choco install sass` according to the instructions on the [Sass website](https://sass-lang.com/install/), the installed Sass version is for x64 architecture. It seems to be working fine without any issues.

Similarly, I would like to request support for using the x64 version of the module in AspNetCore.SassCompiler. Specifically, I would appreciate it if you could add the configuration for Arm64+Windows to AspNetCore.SassCompiler.props.

We have been using this configuration in production for a while, and so far, we have not encountered any issues on our end.

```diff
--- build/AspNetCore.SassCompiler.props.orig	Mon Nov 13 11:07:34 2023
+++ build/AspNetCore.SassCompiler.props	Fri Aug 18 08:09:20 2023
@@ -10,6 +10,8 @@
   </PropertyGroup>
 
   <PropertyGroup Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'Arm64'">
+    <SassCompilerBuildCommand Condition="$([MSBuild]::IsOSPlatform('Windows'))">$(MSBuildThisFileDirectory)..\runtimes\win-x64\src\dart.exe</SassCompilerBuildCommand>
+    <SassCompilerBuildSnapshot Condition="$([MSBuild]::IsOSPlatform('Windows'))">$(MSBuildThisFileDirectory)..\runtimes\win-x64\src\sass.snapshot</SassCompilerBuildSnapshot>
     <SassCompilerBuildCommand Condition="$([MSBuild]::IsOSPlatform('Linux'))">$(MSBuildThisFileDirectory)..\runtimes\linux-arm64\sass</SassCompilerBuildCommand>
     <SassCompilerBuildSnapshot Condition="$([MSBuild]::IsOSPlatform('Linux'))"> </SassCompilerBuildSnapshot>
     <SassCompilerBuildCommand Condition="$([MSBuild]::IsOSPlatform('OSX'))">$(MSBuildThisFileDirectory)..\runtimes\osx-arm64\src\dart</SassCompilerBuildCommand>
```

**Comment by jcoliz** [comment]
As mentioned above, it would be OK to run x64 dart-sass on Arm64 build. As this is a build-time step, it's fine to run it under x64 emulation. This would allow us to build our Arm native apps on Arm native toolchain.

**Comment by sleeuwen** [comment]
@XenonAbe  @jcoliz 
I can't test this as I don't have access to a windows arm system, but as @XenonAbe  mentioned you currently already use this I don't see a reason not to add it.

**Comment by jcoliz** [comment]
@koenvzeijl Thank you! Confirmed 1.69.7 is working great!!
