### ISSUE TITLE
Blazor WASM Net7.0 - Scss to css seems to happen after building the application

### ISSUE THREAD

**Issue by MarkOWiesemann** [koenvzeijl/AspNetCore.SassCompiler#150]
**Describe the bug**
I am experimenting with Sass and wanted to try Sass out but it seems like the style.css is already built before the compiler starts its task.
![image](https://github.com/koenvzeijl/AspNetCore.SassCompiler/assets/95537435/c04caf6e-6b58-4f65-a88b-cbaacaaad5c9)

Is there a workaround?

**To Reproduce**
1. Create Blazor WASM .NET 7.0
2. Add AspNetCore.SassCompiler
3. Add an isolated Scss file
4. Build
5. See no changes

**Expected behavior**
Scss should be compiled before the styles.css is created

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version 1.66.0

**Comment by sleeuwen** [comment]
Hi @MarkOWiesemann ,

I've tried this with the latest 1.69.7 version of the package and it generates the .css before creating the .styles.css file for me.

**Comment by MarkOWiesemann** [comment]
@sleeuwen you can close this issue. I am not working on the project using this anymore and don't have the time to look back into it.
