### ISSUE TITLE
BeforeTargets="Build" is not sufficient to include CSS in build output

### ISSUE THREAD

**Issue by mikes-gh** [koenvzeijl/AspNetCore.SassCompiler#170]
**Describe the bug**
The current [`BeforeTargets="Build;ResolveScopedCssInputs;BundleMinify"`](https://github.com/koenvzeijl/AspNetCore.SassCompiler/blob/d4cca8e3faa08c59fa0c52a9cd3b362e6fe7ea9b/AspNetCore.SassCompiler/build/AspNetCore.SassCompiler.targets#L10) is not sufficient to include the generated assets in a Blazor library.

I have to use a copy of the library and use `BeforeTargets="BeforeBuild"`in order for the generated css to be included in published output without building twice.

**Expected behaviour**
Include the generated css in build output even if it doesn't exist (e.g. in a clone publish scenario such as a CI pipeline).

**Desktop (please complete the following information):**
 - OS: macOS Linux and probably windows
 - Browser Any
 - Version Any

**Comment by sleeuwen** [comment]
Hi @mikes-gh ,

I'm not using Blazor myself, but we do have a Blazor sample app in this repository which does correctly generate scoped css from a scss file with a single build. Do you know if there is any difference between a Blazor app and a Blazor library?
It would be helpful if you could provide a repo/instructions to reproduce the problem so we can investigate it further.

Thanks

**Comment by mikes-gh** [comment]
@sleeuwen Thanks for the response.  The CSS is generated in my scenario as well.  
However, if you do a `dotnet pack` or `dotnet publish` from a clean build (no CSS previously generated) the CSS will not be included since BeforeTargets="Build" happens after MSBuild analyses the staticwebassets to include.
This means the below files would be missing and the library broken.
<img width="274" alt="image" src="https://github.com/koenvzeijl/AspNetCore.SassCompiler/assets/16208742/ad21ee3b-55ab-4e4f-93bd-2e49aa0b8942">

I'll work on a repo hopefully with the sample projects in this lib.

**Comment by mikes-gh** [comment]
@sleeuwen thankyou for spending time on this.  I spent several days on this and could never get it working.  I was using an older version of `AspNetCore.SassCompiler` although AFAICS only changes recently are to do with source target.  I'll confirm you steps this end and report back.  I'll also need to check dotnet publish of our site as that is single target and it may be a timing thing that `MudBlazor.min.css` gets included in the pack as MudBlazor is built 3 times. net6/7/8.

**Comment by mikes-gh** [comment]
@sleeuwen Did you change this line
https://github.com/MudBlazor/MudBlazor/blob/5717ee8139bf63e6ef15f20ebefca11d07937086/src/MudBlazor/MudBlazor.csproj#L92

**Comment by sleeuwen** [comment]
@mikes-gh yes, in the item group for that target is where I added the line from the second diff

**Comment by sleeuwen** [comment]
Ahh I didn't notice the BeforeBuild there, I'll see if I can try some more things later this week

**Comment by mikes-gh** [comment]
Thanks for your time on this.  I'll have a look too.  You have stumbled on a good workaround though.  I still think `BeforeTargets="Build"` is not enough.  However, changing it to before build means your GitHub repo will break, since using before build required a precompiled library to work and won't work with project references.,

**Comment by mikes-gh** [comment]
@sleeuwen I spent some time on it today see below PR in MudBlazor.
I can't seem to get MudBlazor.min.css included in the pack.

https://github.com/MudBlazor/MudBlazor/pull/8268
`cd src/MudBlazor`
`dotnet pack -c Release -v diag > build.log`

When I check the logs it all seems to be OK.
Note the MudBlazor.min.css is included in the Content 3 times (net6/7/8) but never ends up in the static assets directory

**Comment by mikes-gh** [comment]
After spending a few hours on this I am beginning to think this is an incremental build issue.
I can get it all to work if I clone the repo and use dotnet commands to pack or publish and the required files are included.
This is using the package as is without any `BeforeTargets` overides.

**Comment by sleeuwen** [comment]
Hi @mikes-gh,
I may have found a solution, it seems that when packing your project it resolves the `@(Content)` items before the sass is compiled to css, in a target named ResolveProjectStaticWebAssets. I've added that target to the `BeforeTargets` for the "Compile Sass" target and when I run it locally I do now get the css published in the staticwebassets folder within the nuget.
I've published a fix for this and it should be on nuget shortly as version 1.71.1.1. Can you see if that version works for you as well? if not please reopen this issue and I can look into it further.

**Comment by mikes-gh** [comment]
Thanks @sleeuwen.  I have deployed the fix to MudBlazor Repo.   I'll need to keep an eye on things but so far this looks like a fix.  Thanks for all your time on this

**Comment by mikes-gh** [comment]
Just reporting back.
Did a release via our CI pipeline and everything is working as expected.
![image](https://github.com/koenvzeijl/AspNetCore.SassCompiler/assets/16208742/2cf55315-7601-4ee4-a118-2d8da92f3d95)

No need to mess around with the "@Content variables either so project file is significantly simpler.
Thanks a lot 🙏
