### ISSUE TITLE
Disable .map file generation

### ISSUE THREAD

**Issue by gumbarros** [koenvzeijl/AspNetCore.SassCompiler#175]
Is there a flag to disable map file generation 👀?

**Comment by adiessl** [comment]
You need to specify `--no-source-map` in the `Arguments` of the `Configuration` if you want to disable source map generation. See https://github.com/koenvzeijl/AspNetCore.SassCompiler/blob/master/README.md#available-options for additional information.

**Comment by sleeuwen** [comment]
Assuming you're using the new `ISassCompiler` feature given your last created issue, the arguments passed in are passed to the dart-sass executable without modification. The default for dart-sass is to generate a source map, but this can be disabled using the `--no-source-map` option. For all available options you should check the dart-sass documentation: https://sass-lang.com/documentation/cli/dart-sass/

**Comment by gumbarros** [comment]
> You need to specify `--no-source-map` in the `Arguments` of the `Configuration` if you want to disable source map generation. See https://github.com/koenvzeijl/AspNetCore.SassCompiler/blob/master/README.md#available-options for additional information.

Thanks, this will do the job, I will try at the morning and close the issue if it works.
