### ISSUE TITLE
Allow `IOptions<SassCompilerOptions>`

### ISSUE THREAD

**Issue by gumbarros** [koenvzeijl/AspNetCore.SassCompiler#189]
I'm getting sass executable not found on IIS. (Runtime Sass compilation)

Solved with deploying the executable and this:

```
using AspNetCore.SassCompiler;

[assembly:SassCompiler("Sass\\dart.exe","Sass\\Sass.snapshot")]
```

Please allow an `IOptions<SassCompiler>`with the path, this feels so hacky

**Comment by sleeuwen** [comment]
Hi @gumbarros ,
Did you add `<SassCompilerIncludeRuntime>true</SassCompilerIncludeRuntime>` to your csproj that references this nuget? (See the [readme section for runtime compilation](https://github.com/koenvzeijl/AspNetCore.SassCompiler?tab=readme-ov-file#compiling-scss-at-runtime)). As that should automatically include the required files and allow it to find it at runtime.

**Comment by gumbarros** [comment]
> Hi @gumbarros ,
> Did you add `<SassCompilerIncludeRuntime>true</SassCompilerIncludeRuntime>` to your csproj that references this nuget? (See the [readme section for runtime compilation](https://github.com/koenvzeijl/AspNetCore.SassCompiler?tab=readme-ov-file#compiling-scss-at-runtime)). As that should automatically include the required files and allow it to find it at runtime.

Yes, works fine at my machine, just IIS don't find the executable even after changing the user.

**Comment by gumbarros** [comment]
Thank you very much, let me know when it's released so I can test at IIS
