### ISSUE TITLE
Multiple source/target, .min naming, and earlier build step for Blazor

### ISSUE THREAD

**Issue by TheAtomicOption** [koenvzeijl/AspNetCore.SassCompiler#27]
**Issue**
I like the simplicity of this nuget, and was hoping to use this to compile sass to scoped css files for a Blazor Server project. This currently doesn't work as expected for three reasons.

1. AFAICT SassCompiler doesn't have a way to name compressed output files `[file].min.css` instead of `[file].css` when doing many to many. 
1. SassCompiler targets before CopyToOutputDirectory, so it does not run itself before the Blazor build step that aggregates scoped css files into `[assemblyname].min.css` 
2. SassCompiler only accepts one input/output pair. While sass's many/many syntax can compile all the scss files in a Blazor project's /Pages directory into their component-scoped css file counterparts, it cannot at the same time compile global styles in a /Styles directory destined for wwwroot/css.

**Proposed solution**

The SassCompiler object in appsettings.json could hold a list of input/target/argument sets which would be run in series using the order in which they are listed.

The SassCompiler build step could be targeted early enough that the compiled .css files are available for the Blazor css aggregation build step to find.

**Alternatives**
I could potentially add a separate post build step to rename minified css files to have `.min`.

Maybe there's a clever way to hack in adding .min via the attributes or targetfolder with the current code? I don't believe dart sass supports renaming outside of one to one file compilation, but there may be commandline/powershell type tricks to do it. I don't enough about what MSBUILD could carry through from parameters yet to answer that.

~our current npm/node.js solution~

**Comment by koenvzeijl** [comment]
Hi @TheAtomicOption , The whole approach to generating CSS has been changed by @sleeuwen  to also support CSS isolation. Could you please try v1.43.5.1 and see it this suits your needs? It has now also support for Blazor.

**Comment by koenvzeijl** [comment]
@TheAtomicOption For now I will close this issue. Feel free to open it again if the newly implemented solution doesn't work for you.
