### ISSUE TITLE
“Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. ” in visual studio

### ISSUE THREAD

**Issue by FWindson** [koenvzeijl/AspNetCore.SassCompiler#41]
**Describe the bug**
console error after installing AspNetCore.SassCompiler on Visual studio 2022 (and Visual studio 2020, width .NET 5) :
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	MSB4062
未能从程序集 C:\Users\Windson\.nuget\packages\aspnetcore.sasscompiler\1.44.0\build\..\lib\netcoreapp3.1\AspNetCore.SassCompiler.dll 加载任务“AspNetCore.SassCompiler.CompileSass”。Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. 系统找不到指定的文件。 请确认 <UsingTask> 声明正确，该程序集及其所有依赖项都可用，并且该任务包含实现 Microsoft.Build.Framework.ITask 的公共类。	SassCompilerWeb	C:\Users\Windson\.nuget\packages\aspnetcore.sasscompiler\1.44.0\build\AspNetCore.SassCompiler.targets	7	

**To Reproduce**
1. Install AspNetCore.SassCompiler by nutget;
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/20305980/145324616-a3487ea1-84ee-472f-8832-717b726f04d2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Version: 10.0.19044

**Additional context**
I try ver 1.44 and 1.43.5.1 on visual studio 2022 and visual studio 2020 but get the same error, but not any error on Rider 2021.2。

**Comment by FWindson** [comment]
I found that AspNetCore.SassCompiler 1.43.5(or lower version) works, 1.43.5.1(or higher version) console error on visual studio.

**Comment by sleeuwen** [comment]
Hi @FWindson,
Thanks for reporting the issue. In version 1.43.5.1 we changed the way we call the sass process to allow for more flexibility, but as you found out it didn't work correctly when run in VS.
This should now be fixed and available in v1.44.0.1. If that version still doesn't workf or you, feel free to reopen this issue.
