### ISSUE TITLE
Changing Build Task Event

### ISSUE THREAD

**Issue by salarcode** [koenvzeijl/AspNetCore.SassCompiler#52]
Hi, first of all thanks the compiler package it really helps.

I'm trying to use both `BuildBundlerMinifier` and your sass compiler but sass msbuild task is running after the one for  `BuildBundlerMinifier`.
This is causing me some trouble as bundle needs to happen after the sass compile.

Here is what is configured for  `BuildBundlerMinifier` 
`<Target Name="BundleMinify" AfterTargets="CompileTypeScriptWithTSConfig" BeforeTargets="BeforeCompile" Condition="'$(RunBundleMinify)' != 'False'">`

Maybe if you change your task target things get in order?
Here is yours: 
https://github.com/koenvzeijl/AspNetCore.SassCompiler/blob/dc9a489fd44fe06ad7958852ae624b43a284edf7/AspNetCore.SassCompiler/build/AspNetCore.SassCompiler.targets#L6

**Comment by sleeuwen** [comment]
Hi! Thanks for reporting the issue, I've updated the BeforeTargets to run before BundleMinify (if it exists). This is available in version 1.47.0 that we just published.

**Comment by salarcode** [comment]
Confirming that it works, thanks
