### ISSUE TITLE
Invalid JSON String - JSON does not support comments

### ISSUE THREAD

**Issue by RacerDelux** [koenvzeijl/AspNetCore.SassCompiler#73]
**Describe the bug**
SassCompiler errors out when comments are present in appsettings.json

**To Reproduce**
Add a comment in your appsettings.json file.

**Expected behavior**
Comments are ignored

**Screenshots**
![image](https://user-images.githubusercontent.com/2667344/166173534-2068988b-1bae-436c-a57a-8b871ca31739.png)

**Comment by sleeuwen** [comment]
Are you sure the problem is because of comments in the app settings.json? If so can you provide an example file with which you get this error.

We use comments in the appsettings.json in multiple of our examples which are able to build correctly (e.g. https://github.com/koenvzeijl/AspNetCore.SassCompiler/blob/master/Samples/AspNetCore.SassCompiler.Sample/appsettings.json)

**Comment by andez2000** [comment]
I had the same issue tonight (just to piggy back on the problem)

I copied the config from https://github.com/koenvzeijl/AspNetCore.SassCompiler#configuration into sasscompiler.json

```
{
  "SassCompiler": {
    "SourceFolder": "Styles",
    "TargetFolder": "wwwroot/css",
    "Arguments": "--style=compressed",
    "GenerateScopedCss": true,
    "ScopedCssFolders": ["Views", "Pages", "Shared", "Components"],
    
    // You can override specific options based on the build configuration
    "Configurations": {
      "Debug": { // These options apply only to Debug builds
        "Arguments": "--style=expanded"
      }
    }
  }
}
```

Noticed this error when I ran.

**Comment by adiessl** [comment]
You probably read over the following sentence (just as I did), @andez2000:
>when using sasscompiler.json the configuration should not be nested under the key SassCompiler but added directly on the root object

So the content of `sasscompiler.json` should be:

```json
{  
  "SourceFolder": "Styles",
  "TargetFolder": "wwwroot/css",
  "Arguments": "--style=compressed",
  "GenerateScopedCss": true,
  "ScopedCssFolders": ["Views", "Pages", "Shared", "Components"],
  
  // You can override specific options based on the build configuration
  "Configurations": {
    "Debug": { // These options apply only to Debug builds
      "Arguments": "--style=expanded"
    }
  }  
}
```

**Comment by koenvzeijl** [comment]
Do you prefer making this statement bold in the readme or add a small extra section for sasscompiler.json to remove confusion?

**Comment by adiessl** [comment]
I would say having one code snippet for `appsettings.json` and one for `sasscompiler.json` is probably the best way to avoid confusion. This also allows simply copying the configuration without having to adjust it afterwards.

**Comment by andez2000** [comment]
> You probably read over the following sentence (just as I did), @andez2000:
> 
> > when using sasscompiler.json the configuration should not be nested under the key SassCompiler but added directly on the root object
> 
> So the content of `sasscompiler.json` should be:
> 
> ```json
> {  
>   "SourceFolder": "Styles",
>   "TargetFolder": "wwwroot/css",
>   "Arguments": "--style=compressed",
>   "GenerateScopedCss": true,
>   "ScopedCssFolders": ["Views", "Pages", "Shared", "Components"],
>   
>   // You can override specific options based on the build configuration
>   "Configurations": {
>     "Debug": { // These options apply only to Debug builds
>       "Arguments": "--style=expanded"
>     }
>   }  
> }
> ```

I did...  And removed the comments last night and all was ok, cheers.

**Comment by RacerDelux** [comment]
@andez2000 had the exact same experience as me.
I took the config code from the example and tried it both with the `appsettings.json` and the `sasscompiler.json` making the appropriate changes (removing the `SassCompiler` node). It only worked until I removed the comments andez highlighted in red in the previous comment.

**Comment by sleeuwen** [comment]
@RacerDelux there was an issue with the json comment handling, it should now work with comments in the new version v1.51.0.3. I've also updated the readme and added a warning if we detect the SassCompiler property is used within the sasscompiler.json file.
