### ISSUE TITLE
Support Maui Blazor

### ISSUE THREAD

**Issue by RacerDelux** [koenvzeijl/AspNetCore.SassCompiler#74]
**Is your feature request related to a problem? Please describe.**
Hot Reload not working on Maui Blazor projects.

**Describe the solution you'd like**
Support for Maui Blazor Projects.

**Describe alternatives you've considered**
There really isn't any.

**Additional context**
I also get this error the second time I try to build a project:
![image](https://user-images.githubusercontent.com/2667344/166174146-83825360-ec2a-4df3-93d6-dd6dc4c2b693.png)

**Comment by sleeuwen** [comment]
Hi, first of all I want to say that I haven't used Maui nor do I have the time to look into it, so this answer is based on what I do know regarding Blazor WebAssembly.

We currently don't support the .NET hot reload functionality with scss files. In ASP.NET Core/Blazor server we can work around this by using the sass watch command that will automatically recompile the scss whenever it changes, which can then trigger the hot reload functionality as the .css files have changed. 
In Blazor WebAssembly we can't run the watcher as we can't spawn the process to watch the files or even get the files from the file system (as we're in the browser sandbox).

As far as I know there isn't a way for us to hook into the hot reload functionality for custom file extensions.

Regarding the second error you're getting, are you using the latest version? I have seen that before but thought to have fixed it. If you are using the latest version, then it's a bug.

**Comment by RacerDelux** [comment]
I had not heard back on this yet, any thoughts?

**Comment by sleeuwen** [comment]
Hi @RacerDelux , Sorry for the delay, I've fixed the issue about the duplicate app.css asset. It seems like maui is more restrictive about duplicate content files as we always included all generated css files in the `<Content />` itemgroup, but if they were already generated from a previous build, they would already be in the `<Content />` group thus resulting in duplicate entries. For the other applications we've tried it with this wasn't an issue but apparently for MAUI it is. The linked PR should fix this issue and is included in version 1.54.4.1. Please let me know if that fixes the issue for you and if not feel free to reopen the issue.
