### ISSUE TITLE
SassCompilerHostedService: sass command not found, not watching for changes.

### ISSUE THREAD

**Issue by LucGosso** [koenvzeijl/AspNetCore.SassCompiler#77]
**Describe the bug**
We're getting: 

fail: AspNetCore.SassCompiler.SassCompilerHostedService[0]
      sass command not found, not watching for changes.

**To Reproduce**
We dont know really, we use .net6 with several components (MVC + BlazorServer)

with .net5 it worked, some where on the way adding dependencis and upgrade packages, it stopped working. 

we use in appsettings.json

  "SassCompiler": {
    "SourceFolder": "wwwroot/scss",
    "TargetFolder": "wwwroot/css",
    "Arguments": "--style=compressed"
  }

**Expected behavior**
Should compile and watch

**Screenshots**

from cmd: 

fail: AspNetCore.SassCompiler.SassCompilerHostedService[0]
      sass command not found, not watching for changes.

**Additional context**
Any idea where to start debuging? "sass command not found" what sass command?

**Comment by LucGosso** [comment]
looks like we are missing "bin\\debug\\.net6\\runtimes\\win-x64\\src\\dart.exe" ... missing reference?

**Comment by LucGosso** [comment]
So downgrading to version 1.50.0 works, file is copied to bin\debug\.net6\runtimes\win-x64\src\dart.exe

but not on 1.50.0.1 or later.

**Comment by DatReki** [comment]
Seem to have the same issue. Have an ASP.NET Core MVC project which uses .net 5 and is having the same issue. Downgrading to 1.50.0 also fixed it for me.

**Comment by sleeuwen** [comment]
This should now be fixed in the latest version v1.51.0.3
