### ISSUE TITLE
in-place compilation

### ISSUE THREAD

**Issue by patricksadowski** [koenvzeijl/AspNetCore.SassCompiler#98]
**Is your feature request related to a problem? Please describe.**
I hoped to move from [LibSassBuilder](https://github.com/johan-v-r/LibSassBuilder) to [DartSassBuilder](https://github.com/deanwiseman/DartSassBuilder) but the latter one seems to be dead. What I like about _DartSassBuilder_ is the in-place compilation of scss files. Css files are located beside scss files. No input or output folder needed.

**Describe the solution you'd like**
During the build process find all scss files in a project and compile them in-place. Use the directory of the scss file. Simply run scss compilation in folders where scss files are located. This would make configuration of source and destination folder obsolete.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by koenvzeijl** [comment]
Hi @patricksadowski , I totally get what you mean. But it's actually optional to use the input and output folders as you can also make use of the `ScopedCssFolders` and set `GenerateScopedCss` to true

**Comment by patricksadowski** [comment]
My current sasscompiler.json contains
```json
{
    "Arguments": "--no-source-map --style=compressed",
    "ScopedCssFolders": ["."]
}
```
and it's working. So, the thanks are yours.

Now, I have to copy the configuration to several projects in the same repo. I would like to place the configuration once in root. That would be a great feature: use the configuration up in the directory tree. Even better would be a "install and forget" package for a simple sass compilation use case without configuration 😉

**Comment by koenvzeijl** [comment]
@patricksadowski We have an install and forget option as it already uses the defaults. But the default looks in the `/Styles` folder and compiles the files to the `wwwroot/css` folder. I think this is the most common use case. Do you agree? I understand that using the ScopedCssFolders wildcard is very useful for your project but may cause unwanted files to be generated for other users. Please tell me if I overlook something here.

**Comment by patricksadowski** [comment]
@koenvzeijl I agree. We changed some points in our repo so your package fits better.
